/*
James Wagner
CSC 4125/5125 Fall 2021
Practice Schema
*/

DROP TABLE Orders;
DROP TABLE Part;
DROP TABLE Supplier;
DROP TABLE Customer;


CREATE TABLE Customer(
	C_ID NUMBER,
	C_Name VARCHAR(20),
	C_City VARCHAR(25),
	C_Phone CHAR(12),
	CONSTRAINT CusomterPK PRIMARY KEY (C_ID)
);

CREATE TABLE Supplier(
	S_ID NUMBER,
	S_Name VARCHAR(20),
	S_City VARCHAR(25),
	S_Phone CHAR(12),
	CONSTRAINT SupplierPK PRIMARY KEY (S_ID)
);

CREATE TABLE Part(
	P_ID NUMBER,
	P_Name VARCHAR(20),
	P_Color VARCHAR(25),
	P_Size NUMBER(3),
	P_Price NUMBER(6,2),
	CONSTRAINT PartPK PRIMARY KEY (P_ID)
);

CREATE TABLE Orders(
	O_ID NUMBER,
	O_CustID NUMBER,
	O_SuppID NUMBER,
	O_PartID NUMBER,
	O_Date DATE,
	O_Shipmode VARCHAR(10),	
	CONSTRAINT OrderPK PRIMARY KEY (O_ID),
	CONSTRAINT CustFK FOREIGN KEY (O_CustID) REFERENCES Customer(C_ID),
	CONSTRAINT SuppFK FOREIGN KEY (O_SuppID) REFERENCES Supplier(S_ID),
	CONSTRAINT PartFK FOREIGN KEY (O_PartID) REFERENCES Part(P_ID)	
);
